### ISSUE TITLE
Add clickable link to original post

### ISSUE THREAD

**Issue by Al12rs** [bsquidwrd/Quote-Bot#7]
Discord supports links to specific messages that if pressed move the use to the message.
Here is an example: 
https://discordapp.com/channels/265929299490635777/271306913944174601/469994021515952161
where the three numbers are respectively the IDs of the server/channel/message.
Of course the link like this is not looking too good so it would have to under a shorter keyword.
The easiest option would be to just add a *Jump to message* link at the end of the quote.
A really cool thing would instead to be able to press the quote content itself instead, but this would mean finding a way to hide the fact that the text is a link now. It would also have the problem that links of the original message would not work in the quote.
An alternative would be putting the link in the username of the original poster, it would make it cleaner visually but less intuitive.
I would say that Jump to Message is good enough.

**Comment by bsquidwrd** [comment]
Reference for discord.py implementation of getting message URL: http://discordpy.readthedocs.io/en/rewrite/api.html#discord.Message.jump_url
